### ISSUE TITLE
Assisted creation for build target linking list.

### ISSUE THREAD

**Issue by xEnVrE** [qwattash/anrem#1]
Every time I use ANREM for a project and the time comes for me to write the build module mk, it's always a nightmare.
Imagine you have 10 modules containing 5 objects each and you need all these objects linked together to let your wonderful project see the light of life.
Normally I would write standard make stuff like:
SOURCES := $(wildcard *.c)
OBJS := $(patsubst %.c,%.o,$(SOURCES))
and then
build_target : $(OBJS)
    $CC -o $@ $< bla bla bla.
But now, since I started to use ANREM, obtaining very well-designed project tree, I'm getting stuck in the mud with this:
$(call anrem-build, $(BUILD_TARGET)) : $(MOD_one)/obj1.o $(MOD_one)/obj2.o [...] $(MOD_i)/objk.o [...] $(MOD_ten)/obj4.o $(MOD_ten)/obj5.o.
and FINALLY 
    $CC -o $@ $< bla bla bla.
This is a not good feature sir!!! :-1: 

Wouldn't it be great if each of those ten modules could simply ask ANREM to add himself to the build target linking list? (I suggest the name: anrem-add-me-to-the-build).

**Comment by qwattash** [comment]
I see the problem, I've got an idea of how this could work in a generic way; basically I can give you a group/subscriber interface so that you can manage groups of targets and easily refer to them independently from the module position in the source tree.
I'm currently working on the last feature for release 0.1, so expect this to come as 0.1.1!

**Comment by qwattash** [comment]
Implemented in master from version 0.2
